//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graphs.W1.Decomposition1.Reachability.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Graphs.W1.Decomposition1.Reachability.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4  4
        ///1  2
        ///3  2
        ///4  3
        ///1  4
        ///1  4.
        /// </summary>
        public static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4  2
        ///1  2
        ///3  2
        ///1  4.
        /// </summary>
        public static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200 100
        ///150 185
        ///167 174
        ///56 157
        ///58 119
        ///37 177
        ///4 104
        ///46 141
        ///79 106
        ///93 195
        ///7 200
        ///77 128
        ///135 142
        ///116 185
        ///99 129
        ///154 182
        ///38 96
        ///42 51
        ///53 67
        ///42 184
        ///39 138
        ///187 200
        ///105 147
        ///6 26
        ///33 85
        ///102 196
        ///60 62
        ///75 171
        ///31 51
        ///49 129
        ///127 151
        ///125 132
        ///106 107
        ///95 167
        ///128 175
        ///26 189
        ///30 159
        ///34 91
        ///53 142
        ///33 121
        ///113 188
        ///150 197
        ///46 198
        ///101 143
        ///49 186
        ///62 120
        ///3 130
        ///126 135
        ///130 135
        ///71 103
        ///98 109
        ///12 81
        ///50 156
        ///85 176
        ///165 200
        ///80 172
        ///31 124
        ///107 112
        ///35 195
        ///57 83
        ///103 127
        ///134 145
        ///14 60
        ///8 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
    }
}
